[build-system]
requires = [ "flit_core >=3.2,<4" ]
build-backend = "flit_core.buildapi"

[project]
name = "bsb-hdf5"
version = "6.0.1"
readme = "README.md"
requires-python = ">=3.10,<4"
dynamic = [ "description" ]
classifiers = [
  "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)"
]
dependencies = [ "bsb-core~=6.0" ]

  [[project.authors]]
  name = "Robin De Schepper"
  email = "robin@alexandria.sc"

  [[project.authors]]
  name = "Dimitri Rodarie"
  email = "dimitri.rodarie@unipv.it"

  [project.license]
  file = "LICENSE"

[project.entry-points."bsb.storage.engines"]
hdf5 = "bsb_hdf5"

[dependency-groups]
test = [ "bsb-core[parallel]", "bsb-test~=6.0", "coverage>=7.3" ]
docs = [
  "sphinxemoji~=0.2",
  "toml~=0.10",
  "furo~=2024.0",
  "sphinx-copybutton~=0.5",
  "sphinxext-bsb~=6.0"
]
dev = [ "pre-commit~=3.5", "ruff>=0.8.2" ]

[tool.uv]
default-groups = [ "dev", "docs", "test" ]

[tool.uv.sources.bsb-core]
path = "../bsb-core"
editable = true

[tool.uv.sources.bsb-hdf5]
path = "../bsb-hdf5"
editable = true

[tool.uv.sources.bsb-test]
path = "../bsb-test"
editable = true

[tool.uv.sources.sphinxext-bsb]
path = "../../libs/sphinxext-bsb"
editable = true

[tool.flit.module]
name = "bsb_hdf5"

[tool.coverage.run]
branch = true
source = [ "bsb_hdf5" ]

[tool.coverage.report]
exclude_lines = [ "if TYPE_CHECKING:" ]
show_missing = true

[tool.ruff]
exclude = [ ".ruff_cache", ".svn", ".tox", ".venv", "dist" ]
line-length = 90
indent-width = 4

  [tool.ruff.format]
  quote-style = "double"
  indent-style = "space"
  skip-magic-trailing-comma = false
  line-ending = "auto"
  docstring-code-format = true
  docstring-code-line-length = 90

  [tool.ruff.lint]
  select = [ "E", "F", "UP", "B", "SIM", "I" ]
  ignore = [ ]
  fixable = [ "ALL" ]
  unfixable = [ ]
