name: Check public API

on: [workflow_call]

jobs:
  check-api:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - name: Install apt dependencies
      run: |
        sudo apt update
        # Install `libopenmpi` for MPI
        sudo apt install openmpi-bin libopenmpi-dev

    - name: Check public APIs
      run: |
        # Manually set the NX BASE and HEAD variables.
        # see https://github.com/dbbs-lab/bsb/issues/152
        NX_BASE=origin/main
        if [ "${{ github.ref }}" == "refs/heads/main" ]; then
          NX_BASE="${NX_BASE}~1"
        fi
        ./nx affected -t check-api --base=$NX_BASE --head=HEAD
      env:
        NX_DAEMON: false
