name: Validate Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  validate-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: PR Conventional Commit Validation
        uses:  ytanikin/PRConventionalCommits@1.3.0
        with:
          task_types: '["feat","fix","docs","test","ci","refactor","perf","revert"]'

  get-modified:
    runs-on: ubuntu-latest
    if: github.event.action != 'edited'
    outputs:
      matrix: ${{ steps.get-affected.outputs.packages }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install nodejs
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash
          \. "$HOME/.nvm/nvm.sh"
          nvm install --lts

      - name: Derive appropriate SHAs for base and head for `nx affected` commands

      - name: Get affected projects
        id: get-affected
        run: |
          # Manually set the NX BASE and HEAD variables.
          # see https://github.com/dbbs-lab/bsb/issues/152
          NX_BASE=origin/main
          if [${{ github.ref }} == "refs/heads/main" ]; then
            NX_BASE="${NX_BASE}~1"
          fi
          NX_HEAD=${{ github.sha }}
          # Run the nx command once to install required npm libs
          # so that the logs of the installation do not pollute the 
          # output of the next command
          ./nx show projects
          # Here we extract the list of nx bsb projects and store 
          # them as a list that can be parsed in the next job
          packages=$(./nx show projects --projects "packages/*" --affected)
          packages=[\"$(echo $packages | sed -r 's/[ ]+/", "/g')\"]
          echo "packages=$packages" >> $GITHUB_OUTPUT
  preview-docs:
    needs: [ get-modified ]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: ${{ fromJSON(needs.get-modified.outputs.matrix) }}
    steps:
      - name: Preview BSB Readthedocs
        uses: readthedocs/actions/preview@v1
        with:
          project-slug: ${{ matrix.package }}
