name: Build and test Pull Request

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-api:
    uses: ./.github/workflows/check-api.yml
  build:
    uses: ./.github/workflows/build.yml
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  docs:
    uses: ./.github/workflows/docs.yml
  ruff:
    uses: ./.github/workflows/ruff.yml
